In [15]:
import syft as sy

domain = sy.login(email="vovik.01@mail.ru", password="20012002", url="localhost",port=8082)

Connecting to localhost... done! 	 Logging into default_node_name... done!


In [16]:
domain.name

'default_node_name'

In [137]:
domain.datasets

In [135]:
domain.store

[<ndarrayPointer -> default_node_name:c23e7b0d84804d90a3c47c5b557d974f, status=Ready>, PointerId: 269cec4ebfb44cd7a6e3cb6f9ef28a5f
Status: Ready
Representation: array([0.39444265, 0.25869335, 0.04998311, 0.32064649, 0.49108799,
       0.24017843, 0.38556736, 0.02632687, 0.09089151, 0.33795282,
       0.20192422, 0.34015985, 0.1891005 , 0.15916954, 0.27384384,
       0.45744493, 0.45142605, 0.17172932, 0.4945963 , 0.29527101,
       0.23135296, 0.26170357, 0.10945676, 0.22770408, 0.37139488,
       0.41982661, 0.11936459, 0.47025888, 0.07909826, 0.08226931,
       0.40283967, 0.09272775, 0.04633603, 0.19361701, 0.35316273,
       0.04651331, 0.04740458, 0.16758583, 0.28280608, 0.47739929,
       0.03008233, 0.20518273, 0.206953  , 0.07882973, 0.39011885,
       0.3402425 , 0.05520941, 0.13198145, 0.04820697, 0.4041902 ,
       0.40001666, 0.28350875, 0.08688435, 0.07064985, 0.15658366,
       0.46741559, 0.36611453, 0.31240219, 0.43148175, 0.46558217,
       0.46102279, 0.21075794, 0.28645151, 0.08409596, 0.10256258,
       0.37673079, 0.16831747, 0.48948902, 0.38929614, 0.32606894,
       0.1109154 , 0.31062547, 0.37676349, 0.18993769, 0.20307844,
       0.43367656, 0.26973604, 0.16115723, 0.13612656, 0.47691142,
       0.149817  , 0.23016024, 0.34134135, 0.223915  , 0.12091658,
       0.08109732, 0.02078137, 0.34909899, 0.18328045, 0.36563426,
       0.18132843, 0.18728081, 0.16461246, 0.17980942, 0.34177514,
       0.05856149, 0.18099283, 0.2400521 , 0.38933969, 0.36109122,
       0.44369061, 0.44128242, 0.06054705, 0.28302936, 0.49463334,
       0.45335292, 0.18556131, 0.35315011, 0.34028511, 0.37832298,
       0.24718582, 0.03428371, 0.1283905 , 0.36675356, 0.20546434,
       0.41553654, 0.47493313, 0.25089893, 0.35312172, 0.20397225,
       0.32555029, 0.499262  , 0.04766702, 0.24035479, 0.07023844,
       0.39890476, 0.09669918, 0.35399151, 0.14895712, 0.40714865,
       0.11647521, 0.19466243, 0.14288026, 0.16673097, 0.21839073,
       0.21103186, 0.09221425, 0.44193927, 0.39379693, 0.37356029,
       0.2193067 , 0.26123972, 0.09171147, 0.03911494, 0.48701908,
       0.31905368, 0.175292  , 0.20647922, 0.03091847, 0.07983071,
       0.28496402, 0.15964435, 0.12033645, 0.16568463, 0.44438201,
       0.47423227, 0.44483362, 0.0486581 , 0.09446329, 0.23283969,
       0.48759708, 0.07031663, 0.11660211, 0.46108424, 0.46895608,
       0.27831385, 0.19782532, 0.28136165, 0.07234576, 0.43056046,
       0.41939066, 0.07095747, 0.48665456, 0.48581606, 0.16953503,
       0.14321924, 0.34584985, 0.48375405, 0.32636976, 0.06792662,
       0.05342349, 0.16461663, 0.32829687, 0.15749317, 0.18069965,
       0.18656158, 0.31643465, 0.06459589, 0.30808556, 0.42172603,
       0.09086338, 0.14063022, 0.35782233, 0.47250149, 0.24023544,
       0.03707843, 0.19300672, 0.27790015, 0.09141238, 0.39057583,
       0.37465317, 0.29955758, 0.33158862, 0.34864411, 0.44748742,
       0.18287238, 0.29813455, 0.07546727, 0.31783961, 0.23058892,
       0.1339495 , 0.21083985, 0.24613402, 0.32417959, 0.08153616,
       0.44001197, 0.23043719, 0.14835686, 0.43031618, 0.45701568,
       0.49109299, 0.36634435, 0.32999626, 0.38549391, 0.4202455 ,
       0.46071751, 0.49455572, 0.02095587, 0.43987096, 0.19249848,
       0.48388508, 0.18111228, 0.38231737, 0.03669693, 0.22374307,
       0.28628752, 0.42873891, 0.35894284, 0.13483923, 0.11439485,
       0.42221937, 0.34739842, 0.35104506, 0.18257147, 0.16813729,
       0.19406719, 0.27465937, 0.05711168, 0.48999044, 0.38386011])

(The data printed above is synthetic - it's an imitation of the real data.), PointerId: 8b367df8c9904218b3fba828c8aea913
Status: Ready
Representation: array([0.24367223, 0.49692464, 0.68960948, 0.74530673, 0.47961362,
       0.24608864, 0.41763334, 0.39415372, 0.3390392 , 0.92887976,
       0.38334936, 0.57247251, 0.91624138, 0.96340964, 0.7825918 ,
       0.40993184, 0.83624178, 0.78349838, 0.84883987, 0.41189976,
       0.81059345, 0.61369217, 0.82916899, 0.71029809, 0.74346465,
 

In [138]:
cancer_dataset=domain.datasets[3]
cancer_dataset

Dataset: testDataset_v3
Description: Our dataset contains test data. There are 31 columns and 250 rows in our dataset.


 assets = my_dataset.assets 

to view receive a dictionary you can parse through using Python
(as opposed to blowing up your notebook with a massive printed table).



In [19]:
domain.privacy_budget

50000.0

In [20]:
print(f'cancer dataset is of type: {type(cancer_dataset["radius_mean"])}')

cancer dataset is of type: <class 'syft.core.tensor.autodp.phi_tensor.TensorWrappedPhiTensorPointer'>


In [21]:
print(f'cancer dataset is of type: {cancer_dataset["radius_mean"].public_dtype}')

cancer dataset is of type: float64


In [134]:
cancer_dataset["radius_mean"]

PointerId: a5ae4169f03349e891642393df44b2a1
Status: Ready
Representation: array([ 5.34815248, 13.54452995,  4.36574328,  6.06309717,  6.95686007,
        0.96395675, 10.00265831, 26.28098573, 27.78894434,  8.52246017,
        6.94653691, 17.99527398, 18.44630459, 20.2295776 ,  5.02370717,
        5.74151002, 19.91547299, 21.65657837, 10.08202739,  6.50908962,
        3.44552806, 26.98055222, 21.19720438, 22.08923808, 12.68520344,
       12.89890345, 21.35052046,  9.45503188, 27.12947752, 22.67632538,
       16.62886791, 20.30596382, 14.86531251, 27.16992597,  6.69025031,
       18.3987789 , 18.41606603,  6.56157542,  9.07501551, 21.59973934,
        5.42693653, 29.00851559, 19.90854231,  1.56953709,  5.27960143,
       22.5727472 , 24.75428701, 18.57416712, 21.02581273, 24.65872023,
       10.46562147, 24.55425515,  7.97875346, 15.09208289, 13.71516947,
        3.57416492, 29.56879918,  1.24330541,  6.73768446, 13.7237291 ,
       10.32660289,  7.23471193, 14.06333233,  3.70569041,  9.

In [23]:
print(f'radius_mean is of type: {type(cancer_dataset)}')

radius_mean is of type: <class 'syft.core.node.common.client_manager.dataset_api.Dataset'>


In [139]:
diagnosis_dataset = domain.datasets[4]
diagnosis_dataset

Dataset: testDataset_v3_diagnosis
Description: Dataset contains diagnosis result. There are 1 column and 250 rows in our dataset.



In [39]:
diagnosis_dataset["diagnosis"]

<TensorPointer -> default_node_name:a912084df00f453dbf646739fa8d35f5, status=Ready>

In [75]:
#diagnosis_dataset["diagnosis"].request(reason="I really need to see this to train my model")

In [37]:
diagnosis_data = diagnosis_dataset["diagnosis"].get(delete_obj=False)

In [41]:
diagnosis_data = diagnosis_data.child

In [198]:
diagnosis_data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0])

In [63]:
published_diagnosis_data = []

In [64]:
published_data.append(diagnosis_data)

In [67]:
published_data1 = np.asarray(published_data)

In [199]:
deboxed_diagnosis = np.array([item for item in diagnosis_data.flatten()]).reshape(diagnosis_data.shape)
data_df_diagnosis = pd.DataFrame(deboxed_diagnosis)

In [205]:
data_df_diagnosis

0
0    1
1    1
2    1
3    1
4    1
..  ..
245  0
246  0
247  0
248  0
249  0

[250 rows x 1 columns]

In [140]:
cancer_dataset

Dataset: testDataset_v3
Description: Our dataset contains test data. There are 31 columns and 250 rows in our dataset.


 assets = my_dataset.assets 

to view receive a dictionary you can parse through using Python
(as opposed to blowing up your notebook with a massive printed table).



In [141]:
assets = cancer_dataset.assets

In [142]:
assets

[{'name': 'radius_mean',
  'id': 'a5ae4169-f033-49e8-9164-2393df44b2a1',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'texture_mean',
  'id': 'fbabbf4d-b89c-433c-8ba7-e0461aa43d1a',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'perimeter_mean',
  'id': '64039aaf-eff2-4551-be75-8d2bb956460f',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'area_mean',
  'id': '9ebed425-7b77-4e71-8919-57f102a36fbb',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'smoothness_mean',
  'id': '1a8b67d2-d369-4831-b892-c975ebc2e335',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'compactness_mean',
  'id': 'd6d7cb36-d243-433f-ba86-28bcb23ed9b6',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'concavity_mean',
  'id': '4c2bdca6-a0f1-4a23-bf78-5491ae1d7765',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'concave points_mean',
  'id': '19b67349-8a87-40ca-83be-ac20ce50b20b',
  'dtype': 'Tensor',
  'shape': '(250,)'},
 {'name': 'symmetry_mean',
  'id': 'ce842f3e-dd64-

In [186]:
conca = cancer_dataset["smoothness_mean"]

In [187]:
conca_public = conca.publish(sigma=0.03)
#conca_public.block_with_timeout(30)
privacy_conca = conca_public.get(delete_obj=False)

In [ ]:
sigmas = [3, 4, 20, 100, 0.03, 0.01, 0.05, 0.03, 0.04, 0.01, 0.05, 0.15, 0.4, 5, 0.01, 0.04, 0.08, 0.01, 0.01, 0.01, 4, 5, 15, 80, 0.015, 0.01, 0.1, 0.1, 0.08, 0.02]

In [188]:
privacy_conca

array([0.11864444, 0.05645477, 0.11837382, 0.17473775, 0.04817363,
       0.11665987, 0.06860185, 0.16500364, 0.12211764, 0.14662416,
       0.12252493, 0.05266265, 0.10081088, 0.07168503, 0.10601742,
       0.11612507, 0.082655  , 0.07723327, 0.08581113, 0.0548599 ,
       0.10383578, 0.14875479, 0.1162827 , 0.10731004, 0.16763324,
       0.09358017, 0.12828245, 0.11426515, 0.09231551, 0.09363924,
       0.10649835, 0.15764235, 0.1262649 , 0.09890487, 0.09114384,
       0.07924426, 0.13997253, 0.0612051 , 0.07291529, 0.09818807,
       0.09039009, 0.10479608, 0.10526146, 0.13194968, 0.0441894 ,
       0.11337109, 0.10308094, 0.09465002, 0.11747774, 0.08524005,
       0.13659825, 0.0614151 , 0.03912001, 0.07670576, 0.04698105,
       0.09111061, 0.15655775, 0.0960961 , 0.06421024, 0.12594139,
       0.14103185, 0.11539852, 0.10013693, 0.09698856, 0.15272368,
       0.0629944 , 0.13641547, 0.09148076, 0.10792956, 0.09199739,
       0.09226859, 0.1196558 , 0.11140548, 0.06042724, 0.04062

In [189]:
published_data = []
sigmas = [3, 4, 20, 100, 0.03, 0.01, 0.05, 0.03, 0.04, 0.01, 0.05, 0.15, 0.4, 5, 0.01, 0.04, 0.08, 0.01, 0.01, 0.01, 4, 5, 15, 80, 0.015, 0.01, 0.1, 0.1, 0.08, 0.02]

for asset_n, sigma_n in zip(assets, sigmas):
    feature = cancer_dataset[asset_n['name']]
    feature_public = feature.publish(sigma=sigma_n)
    feature_public.block_with_timeout(50)
    privacy_feature = feature_public.get(delete_obj=False)
    published_data.append(privacy_feature)

In [163]:
published_data = []

for asset_n in assets:
    feature = cancer_dataset[asset_n['name']]
    feature_public = feature.publish()
    feature_public.block_with_timeout(50)
    privacy_feature = feature_public.get(delete_obj=False)
    published_data.append(privacy_feature)

Exception: Object with id <UID: fa29a7ba73164685a75d30a9f67fc100> still doesn't exist after 50 second timeout.

In [191]:
#published_data

In [192]:
published_data1 = np.asarray(published_data)

In [193]:
deboxed = np.array([item for item in published_data1.flatten()]).reshape(published_data1.shape)
data_df = pd.DataFrame(deboxed)

In [195]:
data_df = data_df.transpose()

In [196]:
data_df

0          1           2            3         4         5   \
0    18.086286   4.414114  116.087050   930.691974  0.143412  0.298124   
1    19.923893  19.192711  146.331954  1369.976433  0.120209  0.084396   
2    18.507012  24.938589  136.237816   915.675139  0.085047  0.173943   
3    10.514660  18.046123   84.470575   462.340169  0.118310  0.270072   
4    16.991358  15.742862  155.073419  1252.894104  0.038675  0.132991   
..         ...        ...         ...          ...       ...       ...   
245  11.806381  23.564845  104.306471   361.225909  0.105863  0.061110   
246   8.669657  20.899122   74.039842   399.070819  0.069216  0.056578   
247  15.731154  28.669632   99.897559   805.566602  0.112722  0.134323   
248   6.392437  24.472415  106.440592   260.592194  0.060083  0.067611   
249   9.640229  16.427830   64.150535   544.290066  0.125975  0.081116   

           6         7         8         9   ...         20         21  \
0    0.347915  0.148719  0.224243  0.091866  ...  28.194959  13.354048   
1    0.046837  0.076572  0.259650  0.059861  ...  22.185857  20.035440   
2    0.235497  0.169796  0.165186  0.057473  ...  18.758430  20.810769   
3    0.250051  0.080651  0.217578  0.093787  ...  18.365369  28.500718   
4    0.200345  0.099479  0.184270  0.046858  ...  18.019774  11.430568   
..        ...       ...       ...       ...  ...        ...        ...   
245  0.000082 -0.021883  0.152473  0.071997  ...   7.611603  23.385427   
246 -0.015671  0.031949  0.130631  0.045341  ...  20.478738  25.589899   
247  0.150630  0.058539  0.134142  0.064412  ...  15.611695  16.085876   
248  0.000536  0.035487  0.166674  0.044635  ...   6.442185  35.739083   
249  0.032032  0.062960  0.133072  0.076443  ...  16.259885  18.639755   

             22           23        24        25        26        27  \
0    188.348764  2040.434892  0.169584  0.666503  0.798946  0.117947   
1    133.772465  2061.882567  0.121126  0.200681  0.393180  0.194093   
2    142.155508  1783.265785  0.153407  0.427753  0.509350  0.458098   
3     97.257999   462.683201  0.205452  0.866499  0.682440  0.153531   
4    156.023187  1704.283845  0.151425  0.216521  0.360241  0.390316   
..          ...          ...       ...       ...       ...       ...   
245   59.279757   422.844507  0.140917  0.097966  0.019184  0.356972   
246   81.461415   422.738999  0.098610  0.148740  0.093967  0.036781   
247  105.467190   618.766629  0.164961  0.585498  0.680721  0.178442   
248   96.461732   474.106925  0.130067  0.123768  0.037361  0.036030   
249   89.511188   516.257920  0.138785  0.144238  0.229035  0.106279   

           28        29  
0    0.533494  0.120726  
1    0.349484  0.093894  
2    0.293332  0.122250  
3    0.718897  0.182292  
4    0.335000  0.076709  
..        ...       ...  
245  0.125814  0.079065  
246  0.406476  0.038115  
247  0.293415  0.104199  
248  0.353073  0.079935  
249  0.326083  0.088597  

[250 rows x 30 columns]

In [ ]:
#МОДЕЛЬ

In [208]:
from sklearn import tree
from sklearn.model_selection import train_test_split

X = data_df
y = data_df_diagnosis

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = tree.DecisionTreeClassifier(criterion='entropy')

clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print("Accuracy:", accuracy)

y_pred = clf.predict([[17.86, 10.55, 118.8, 1005, 0.1166, 0.2779, 0.3051, 0.1491, 0.2499, 0.07811, 1.035, 0.9058, 8.586, 151.6, 0.006319, 0.04931, 0.05359, 0.01566, 0.03016, 0.006109, 24.68, 17.49, 183.8, 2019, 0.1661, 0.6682, 0.7107, 0.2668, 0.4611, 0.1168],
                      [17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189],
                      [12.54, 13.36, 82.46, 526.3, 0.09979, 0.08229, 0.06864, 0.04581, 0.1985, 0.05966, 0.2688, 0.7986, 3.058, 29.56, 0.007462, 0.0186, 0.02587, 0.01715, 0.0215, 0.0029, 15.51, 19.56, 106.7, 721.6, 0.168, 0.1738, 0.242, 0.1298, 0.2959, 0.0756]])
print("Predicted Class Labels: ", y_pred)

Accuracy: 0.86
Predicted Class Labels:  [1 1 0]


In [50]:
feature = cancer_dataset["radius_mean"]

In [51]:
feature_public = feature.publish(sigma=8)

In [52]:
feature_public

<ndarrayPointer -> default_node_name:c23e7b0d84804d90a3c47c5b557d974f, status=Ready>

In [53]:
privacy_feature = feature_public.get(delete_obj=False)

In [54]:
privacy_feature

array([ 12.8641572 ,  15.48831938,  10.61195223,   1.78833553,
        18.82732526,   6.98541344,  20.65810624,   9.01542108,
         6.33364249,  10.79056794,  21.38751487,   9.8670791 ,
        16.59230948,   4.68325787,  18.78932419,   5.99617873,
         8.59176542,  16.94698539,  19.14738927,   6.6251919 ,
         9.46343001,   5.5133595 ,  18.09025244,  11.71994434,
        18.08798944,  25.1517692 ,  29.19441824,  24.94625528,
        -5.90767471,  15.19417097,  13.2269483 ,  12.43159206,
        27.98636335,  22.17048469,  16.20626797,  10.53824836,
        14.44817152,  28.0685493 ,   8.06522249,  21.85263961,
        -4.23334311,  13.64488222,   0.17898191,  16.04836911,
        28.6772661 ,  16.75401998,   8.28166887,   3.60211605,
        15.14728955,   4.83853837,  15.79265243,  15.22712059,
         5.9753279 ,  12.35605813,  10.03723842,  12.0554364 ,
        13.68431606,  17.23670651,  30.18923862,  19.08147075,
         2.43804267,  11.56530995,   2.78421472,  17.87

In [162]:
domain.privacy_budget

114713.10421983823

In [62]:
type(privacy_feature)

numpy.ndarray

In [63]:
privacy_feature.shape

(250,)

In [13]:
ages = family_age_dataset["Age_Data"]

NameError: name 'family_age_dataset' is not defined

In [8]:
ages.public_dtype

dtype('int64')

In [9]:
family_age_dataset["Age_Data"]


PointerId: 6ba49c38ec8643b5a06a8766cd057b3d
Status: Ready
Representation: array([88, 80, 78, 94])

(The data printed above is synthetic - it's an imitation of the real data.)

In [10]:
mean_age_public = ages.publish(sigma=20)


In [11]:
mean_age_public

<ndarrayPointer -> default_node_name:91ec54d31497422b9a00c1669e21d962, status=Processing>

In [12]:
mean_age_public.get(delete_obj=False)

array([32.99935534, 21.47710061, 10.53703462, 10.03608156])

Достаем второй датасет

In [4]:
spiderman_age_dataset=domain.datasets[2]
spiderman_age_dataset

Dataset: Family_Age_Dataset_v2
Description: Our dataset contains the Ages of our four Family members with unique ID's. There are 2 columns and 4 rows in our dataset.



In [14]:
spiderman_age_dataset["Age_Data"]

<TensorPointer -> default_node_name:e50dc5a8c9da44789dce36f7abed7e91, status=Ready>

In [155]:
domain.privacy_budget

22702.50706750542

In [35]:
spiderman_age_dataset["Age_Data"].request(reason="I really need to see this")

In [10]:
ages = spiderman_age_dataset["Age_Data"].get()

In [12]:
type(ages)

syft.core.tensor.tensor.Tensor

In [31]:
spider_mean_age_public = ages.publish()

In [32]:
spider_mean_age_public

<ndarrayPointer -> default_node_name:28d20d85a2d34b439142094ab225c691, status=Processing>

In [33]:
result_arr = spider_mean_age_public.get(delete_obj=False)

[2023-05-18T14:57:30.697545+0500][CRITICAL][logger]][23854] Unable to Get Object with ID <UID: 28d20d85a2d34b439142094ab225c691> from store. Possible dangling Pointer. 'Object not found! for UID: 28d20d85-a2d3-4b43-9142-094ab225c691'


UnknownPrivateException: Unable to Get Object with ID <UID: 28d20d85a2d34b439142094ab225c691> from store. Possible dangling Pointer. 'Object not found! for UID: 28d20d85-a2d3-4b43-9142-094ab225c691'

In [65]:
result_arr

array([17.36214563, 26.46931173, 18.11931484, 21.05759375, 18.38698209,
       16.8739602 ,  6.88442038, 24.95978123,  8.66941377, 15.67948188,
       22.75392723])

In [66]:
mean_age = result_arr.mean()

In [67]:
mean_age

17.928757519642357